### ISSUE TITLE
Documentation: Add Password Requirements to Common Failures

### ISSUE THREAD

**Issue by msidwell** [awslabs/aws-greengrass-labs-dashboard-grafana#8]
**Describe the bug**
When accidentally using a password that doesn't match complexity requirements, the component will fail inexplicably from the view of greengrass.log. This error can only be seen by checking the component-specific logs.

**To Reproduce**
Use a password that does not meet the complexity requirements and not see the true failure reason in greengrass.log.

**Expected behavior**
A common failure explanation in the documentation to cover this scenario.

**Actual behavior**
I had to dig through tons of logs to figure out what happened.

**Environment**
N/A as this is a documentation request.

**Comment by saranyailla** [comment]
Hi, 
Thank you for using this component. Our `README.md` documentation specifies the password requirements as shown below:
>Note that your password must be at least 16 characters long and must include uppercase and lowercase letters, numbers, and special characters

Please let us know if you see that the password requirements in the doc are different from that of the component's. 

Since the documentation already provides the requirements and the component logs also provide the same, do you still suggest that we add it under troubleshooting?
